### ISSUE TITLE
不兼容 Fastlogin 插件?

### ISSUE THREAD

**Issue by misaka00251** [yushijinhun/authlib-injector#104]
```
[11:33:29] [FastLogin Pool Thread #2/INFO]: [FastLogin] Handling player Player1
[11:33:29] [FastLogin Pool Thread #2/INFO]: [FastLogin] Requesting premium login for registered player: Player1
[11:33:30] [FastLogin Pool Thread #3/WARN]: [FastLogin] Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.ClassCastException: class sun.net.www.protocol.http.HttpURLConnection cannot be cast to class javax.net.ssl.HttpsURLConnection (sun.net.www.protocol.http.HttpURLConnection and javax.net.ssl.HttpsURLConnection are in module java.base of loader 'bootstrap')
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class sun.net.www.protocol.http.HttpURLConnection cannot be cast to class javax.net.ssl.HttpsURLConnection (sun.net.www.protocol.http.HttpURLConnection and javax.net.ssl.HttpsURLConnection are in module java.base of loader 'bootstrap')
        at com.github.games647.craftapi.resolver.AbstractResolver.getConnection(AbstractResolver.java:132) ~[?:?]
        at com.github.games647.craftapi.resolver.AbstractResolver.getConnection(AbstractResolver.java:120) ~[?:?]
        at com.github.games647.craftapi.resolver.MojangResolver.hasJoined(MojangResolver.java:69) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:106) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:67) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        ... 3 more
[11:33:59] [Server thread/INFO]: Disconnecting /IP:Port: Took too long to log in
[11:33:59] [Server thread/INFO]: /IP:Port lost connection: Took too long to log in
```

服务器将 `online-mode=false` 并设置有玩家注册系统，但为了考虑正版玩家故使用 [Fastlogin](https://www.spigotmc.org/resources/fastlogin.14153/) 插件来提供快速登录服务。Player1 是一名正版玩家，在服务端不使用 authlib-injector 前可实现进入游戏直接登录。

**Comment by yushijinhun** [comment]
请问为何要关闭此 issue？
