### ISSUE TITLE
Macos通过AI无法正常启动1.13

### ISSUE THREAD

**Issue by outtimes** [yushijinhun/authlib-injector#15]
以下是error logs:
```
[authlib-injector] launched from premain
[authlib-injector] version: 1.1.18-daa6fb4
[authlib-injector] api root: https://i.timewk.cn/api/yggdrasil/
[authlib-injector] prefetched metadata detected
[authlib-injector] httpd is running on port 53185
[authlib-injector] transform [http://skins.minecraft.net/MinecraftSkins/%s.png] to [http://127.0.0.1:53185/MinecraftSkins/%s.png]
[authlib-injector] transform csv using deprecated-api-transform
Exception in thread "Client thread" java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	at net.minecraft.client.main.Main.main(SourceFile:144)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWErrorCallbackI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
[15:04:29] [Client Shutdown Thread/ERROR] [net.minecraft.client.main.Main] Caught previously unhandled exception :
```

**Comment by xfl03** [comment]
emmm我没写入权限，请排一下版

**Comment by yushijinhun** [comment]
去掉 authlib-injector 后可以正常启动吗

**Comment by xfl03** [comment]
理论是不是authlib-injector的问题，并没有以任何形式调用lwjgl相关的内容
请您手动确认一下`.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6.jar`这一文件的完整性

**Comment by outtimes** [comment]
查无此文件，但是游戏通过HMCL的游戏完整性检查且可在Windows环境下正常启动。

**Comment by xfl03** [comment]
请使用PasteBin之类的完整贴一下HMCL的日志

**Comment by yushijinhun** [comment]
无法重现。
