### ISSUE TITLE
玩家进入服务器时报错

### ISSUE THREAD

**Issue by zxj199884** [yushijinhun/authlib-injector#152]
在1.12.2 CatServer核心端，玩家第一次进入时会报错

> [authlib-injector] [ERROR] Could not send response to the client
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.ChunkedOutputStream.
write(ChunkedOutputStream.java:84)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.sendBody(Re
sponse.java:257)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.sendBodyWit
hCorrectTransferAndEncoding(Response.java:227)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.send(Respon
se.java:195)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(
HTTPSession.java:266)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHand
ler.run(NanoHTTPD.java:104)
        at java.lang.Thread.run(Thread.java:750)

第二次进入后就不会这个报错，如果重启服务器的话，在重启的过程中会报这个错误

**Comment by yushijinhun** [comment]
authlib-injector v1.1.42，CatServer 22.01.27 上测试无法重现你的问题，Java 版本 openjdk 1.8.0_312。

请提供你的 authlib-injector、CatServer 以及 Java 版本。

**Comment by yushijinhun** [comment]
authlib-injector v1.1.42，CatServer 22.01.27 上测试无法重现你的问题，Java 版本 openjdk 1.8.0_312。

请提供你的 authlib-injector、CatServer 以及 Java 版本。

**Comment by zxj199884** [comment]
如果需要，我可以把我的服务器端发你测试，因为我用的也是authlib-injector v1.1.42，CatServer 22.01.27 上测试无法重现你的问题，Java 版本 openjdk 1.8.0_312。

**Comment by zxj199884** [comment]
还有一个新的黄色警告：
[01:55:14] [Craft Scheduler Thread - 10/WARN]: Couldn't look up profile properti
es for com.mojang.authlib.GameProfile@754493b[id=597ece07-bb1d-33fd-83db-8d21e77
d5984,name=caigou,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact
 authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeReque
st(YggdrasilAuthenticationService.java:85) ~[YggdrasilAuthenticationService.clas
s:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGam
eProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionSe
rvice.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillPro
fileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSes
sionService.class:?]
        at net.minecraft.tileentity.TileEntitySkull$1.load(TileEntitySkull.java:
92) [awd$1.class:?]
        at net.minecraft.tileentity.TileEntitySkull$1.load(TileEntitySkull.java:
58) [awd$1.class:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
ocalCache.java:3716) [guava-21.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2
424) [guava-21.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache
.java:2298) [guava-21.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[guava-21.0.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-2
1.0.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [g
uava-21.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.j
ava:5147) [guava-21.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(Loc
alCache.java:5153) [guava-21.0.jar:?]
        at net.minecraft.tileentity.TileEntitySkull$3.call(TileEntitySkull.java:
249) [awd$3.class:?]
        at net.minecraft.tileentity.TileEntitySkull$3.call(TileEntitySkull.java:
246) [awd$3.class:?]
        at net.minecraft.tileentity.TileEntitySkull.updateGameprofile(TileEntity
Skull.java:265) [awd.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.applyToItem(
CraftMetaSkull.java:79) [CraftMetaSkull.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.setItemMeta(
CraftItemStack.java:431) [CraftItemStack.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asNMSCopy(Cr
aftItemStack.java:46) [CraftItemStack.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(Craf
tInventory.java:96) [CraftInventory.class:git-CatServer-1.12.2-a8b73e9]
        at pers.tany.yukinoaapi.realizationpart.item.SkullUtil$1.run(SkullUtil.j
ava:49) [%5B前置%5DYukiNoaAPI.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:76) [CraftTask.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-a8b73e9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_312]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?
:1.8.0_312]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0
_312]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0
_312]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.
8.0_312]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1
.8.0_312]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.
8.0_312]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[?:
1.8.0_312]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_
312]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1590) ~[?:1.8.0_312]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1495) ~[?:1.8.0_312]
        at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAu
thenticationService.java:130) ~[HttpAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeReque
st(YggdrasilAuthenticationService.java:66) ~[YggdrasilAuthenticationService.clas
s:?]
        ... 25 more
>

**Comment by yushijinhun** [comment]
> 如果需要，我可以把我的服务器端发你测试，因为我用的也是authlib-injector v1.1.42，CatServer 22.01.27 Java 版本 openjdk 1.8.0_312。

请打包发到 yushijinhun@gmail.con

**Comment by yushijinhun** [comment]
@zxj199884 你发送给我的服务端中有插件需要连接数据库，因此我无法在本地进行测试。请自行使用二分法排查出可能导致问题的插件/Mod。

**Comment by zxj199884** [comment]
已删除需要数据库的插件，希望您能帮我在看看，我看不出有啥导致authlib-injector报错的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yushijinhun/authlib-injector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yushijinhun/authlib-injector] 玩家进入服务器时报错 (Issue #152)





 
@zxj199884 你发送给我的服务端中有插件需要连接数据库，因此我无法在本地进行测试。请自行使用二分法排查出可能导致问题的插件/Mod。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

测试.zip (2.13G, 2022年05月07日 20:38 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0a30333765e8ee15a0c94e6f4063564d00555702505b57541a0504015e4e50500f071e565200004f530706000306050405015653666b64d0d5fae7191c0a146241&code=7037fcdb

**Comment by yushijinhun** [comment]
请**自行排查**可能导致问题的插件/Mod，然后再反馈问题。

**Comment by zxj199884** [comment]
我并没有找到导致authlib-injector报错的插件或者mod




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haowei ***@***.***&gt;; 
发送时间: 2022年4月7日(星期四) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yushijinhun/authlib-injector] 玩家进入服务器时报错 (Issue #152)





 
请自行排查可能导致问题的插件/Mod，然后再反馈问题。

**Comment by yushijinhun** [comment]
你移除所有的插件和Mod后，问题依然存在吗？

**Comment by yushijinhun** [comment]
我在删除你提供的服务端的 `mods` 和 `plugins` 以及 `world` 后一切正常，说明这个问题是由某个 Mod 或者插件造成的。我不提供帮你排查插件/Mod兼容性的服务，请找出有问题的插件/Mod后，再 reopen 这个 issue。
