### ISSUE TITLE
身份验证服务器目前处于宕机状态

### ISSUE THREAD

**Issue by HultimateH** [yushijinhun/authlib-injector#155]
我的服务器情况为 ：MC服务器和皮肤站部署在同一个机器上，具有公网IP，每隔三天就会变化。
我目前遇到的问题：在更换IP后，登陆服务器就会提示“身份验证服务器目前处于宕机状态。请稍后在试，抱歉！”，通过多次登陆才能进服务器。我不清楚这个问题出在皮肤站还是Yggdrasil API插件上面。

下面是服务端  打印的信息：

[12:24:05] [User Authenticator #35/INFO]: Disconnecting com.mojang.authlib.GameProfile@73a8f4e1[id=<null>,name=Tomee,properties={},legacy=false] (/14.105.81.97:60166): Authentication servers are down. Please try again later, sorry!
[12:24:05] [User Authenticator #35/ERROR]: Couldn't verify username because servers are unavailable
[12:24:05] [Server thread/INFO]: com.mojang.authlib.GameProfile@73a8f4e1[id=<null>,name=Tomee,properties={},legacy=false] (/14.105.81.97:60166) lost connection: Authentication servers are down. Please try again later, sorry!
[authlib-injector] [WARNING] Reverse proxy error
java.net.ConnectException: 拒绝连接
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:187)
        at moe.yushi.authlibinjector.httpd.URLProcessor.access$300(URLProcessor.java:46)
        at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:148)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yushijinhun** [comment]
你可以试试指定 `-Dnetworkaddress.cache.ttl=0` 参数禁用 DNS 缓存。

参考：https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/doc-files/net-properties.html#AddressCache
