### ISSUE TITLE
"Could not retrieve profile key pair" error message

### ISSUE THREAD

**Issue by Octol1ttle** [yushijinhun/authlib-injector#188]
Hello. When I start the Minecraft client, this excepion is shown:
```
[10:07:21] [Worker-Main-2/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at eva.a(SourceFile:130) ~[minecraft-1.19.2-client.jar:?]
	at eva.c(SourceFile:69) ~[minecraft-1.19.2-client.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

I am using authlib-injector version 1.2.1.
Because of this error, it is not possible to join servers with `enforce-secure-profile` enabled (which is recommended in the release notes)
I am using the Ely.by authentication server, which does not provide its own keys

**Comment by Octol1ttle** [comment]
Fixed in an update (I lost track)
