### ISSUE TITLE
无法认证问题

### ISSUE THREAD

**Issue by lxzcl** [yushijinhun/authlib-injector#201]
游戏版本1.18.2只带forge
catserver 1.18.2服务端
authlib-injector1.2.2版本
服务端去掉了使用插件和mod
配置：online-mode=true
启动器使用hmcl

客户端信息
Logging started at 2023-03-20T17:12:47.745583200Z
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: https://www.mymc.xyz/api/yggdrasil/
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Httpd is running on port 56793
[authlib-injector] [INFO] Transformed [net.minecraft.client.player.AbstractClientPlayer] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [mcp.mobius.waila.plugin.vanilla.provider.PetOwnerProvider] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.server.network.ServerLoginPacketListenerImpl] with [Username Character Check Transformer]
[authlib-injector] [WARNING] Reverse proxy error
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:192)
	at moe.yushi.authlibinjector.httpd.URLProcessor.access$400(URLProcessor.java:47)
	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:158)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)

服务端信息
前台
[01:14:27] [Server thread/INFO]: com.mojang.authlib.GameProfile@108b2ba8[id=<null>,name=cnmQQ,properties={},legacy=false] (/127.0.0.1:56811) lost connection: Disconnected
log文件
Logging started at 2023-03-20T17:28:31.809149800Z
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: https://www.mymc.xyz/api/yggdrasil
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Httpd is running on port 57186
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.server.network.ServerLoginPacketListenerImpl] with [Username Character Check Transformer]

**Comment by jimmy-sketch** [comment]
我也有同样的问题，但是我是1.9 littleskin,显示无法验证用户名
版本：1.9，原版无插件/模组
![image](https://user-images.githubusercontent.com/110657724/229335115-39ab71c5-6379-4b7f-9c3d-6b4ebc57aa1f.png)
这是日志
14:07:36 INFO]: Starting minecraft server version 1.9
[14:07:36 INFO]: Loading properties
[14:07:36 INFO]: Default game type: SURVIVAL
[14:07:36 INFO]: Generating keypair
[14:07:36 INFO]: Starting Minecraft server on *:25565
[14:07:36 INFO]: Using default channel type
[14:07:37 INFO]: Preparing level "world2"
[14:07:38 INFO]: Preparing start region for level 0
[14:07:39 INFO]: Preparing spawn area: 52%
[14:07:39 INFO]: Done (1.635s)! For help, type "help" or "?"
[14:07:51 INFO]: Disconnecting /127.0.0.1:12174: Failed to verify username!
[14:07:51 INFO]: /127.0.0.1:12174 lost connection: Failed to verify username!
[14:14:42 INFO]: Disconnecting /127.0.0.1:13107: Failed to verify username!
[14:14:42 INFO]: /127.0.0.1:13107 lost connection: Failed to verify username!

**Comment by yushijinhun** [comment]
@lxzcl 由于不活动关闭此 issue。如果你的问题依然存在，请 reopen，并提供完整的控制台日志。如果你用 HMCL，你可以在 JVM 参数中添加 `-Dauthlibinjector.debug`，然后使用调试游戏启动，上传完整的控制台日志。

@jimmy-sketch 你的问题与此 issue 无关，如果你要反馈问题，请新开 issue。
