### ISSUE TITLE
与最新版 CMI 插件冲突

### ISSUE THREAD

**Issue by coldshineb** [yushijinhun/authlib-injector#202]
当在 1.19.4 上使用 CMI 9.4.0.2 和 authlib-injector 时，报出以下错误，停用 authlib-injector 后正常。
测试环境：Debian 10/macOS 13.2.1
Java 17 (OpenJDK 64-Bit Server VM 17.0.6+10)/Java 18 (Eclipse OpenJ9 VM openj9-0.33.1)
已排除插件、服务器核心等自身原因

```
[18:11:01 INFO]: Starting Minecraft server on *:25565
[18:11:01 INFO]: Using default channel type
[18:11:03 INFO]: Paper: Using libdeflate (macOS ARM64 / Apple Silicon) compression from Velocity.
[18:11:03 INFO]: Paper: Using native (macOS ARM64 / Apple Silicon) cipher from Velocity.
[18:11:03 WARN]: java.lang.reflect.InvocationTargetException
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:11:03 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:11:03 WARN]: 	at CMI-9.4.0.2.jar//V5qQqSJ85FeZ2kgx.aFWkHwvcAuHVuMTAIBD1(V5qQqSJ85FeZ2kgx.java)
[18:11:03 WARN]: 	at CMI-9.4.0.2.jar//com.Zrips.CMI.CMI.<init>(CMI.java:170)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:11:03 WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:11:03 WARN]: 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[18:11:03 WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
[18:11:03 WARN]: 	at java.base/java.lang.Class.newInstance(Class.java:645)
[18:11:03 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88)
[18:11:03 WARN]: 	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123)
[18:11:03 WARN]: 	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35)
[18:11:03 WARN]: 	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150)
[18:11:03 WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35)
[18:11:03 WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[18:11:03 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423)
[18:11:03 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[18:11:03 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[18:11:03 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:11:03 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:03 WARN]: Caused by: java.lang.RuntimeException: Failed to load
[18:11:03 INFO]: [CMILib] Loading server plugin CMILib v1.2.5.2
[18:11:03 INFO]: [CMI] Loading server plugin CMI v9.4.0.2
[18:11:03 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:11:03 INFO]: Preparing level "world"
[18:11:04 INFO]: Preparing start region for dimension minecraft:overworld
[18:11:04 INFO]: Time elapsed: 84 ms
[18:11:04 INFO]: Preparing start region for dimension minecraft:the_nether
[18:11:04 INFO]: Time elapsed: 37 ms
[18:11:04 INFO]: Preparing start region for dimension minecraft:the_end
[18:11:04 INFO]: Time elapsed: 31 ms
[18:11:04 INFO]: [CMILib] Enabling CMILib v1.2.5.2
[18:11:06 INFO]: Server version: v1_19_R3 - 1.19.4 - paper
[18:11:07 INFO]: CMI hooked.
[18:11:07 INFO]: Updated (EN) language file. Took 67ms
[18:11:07 INFO]: [CMI] Enabling CMI v9.4.0.2
[18:11:07 ERROR]: Error occurred while enabling CMI v9.4.0.2 (Is it up to date?)
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:315) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java) ~[CMI-9.4.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-468]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-468]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "hgMZmBnTGPAmGOVMQpVS.sfr5bZI3NklRncWEG1SHj" is null
	at hgMZmBnTGPAmGOVMQpVS.RGHmdZuZn9ns7R(hgMZmBnTGPAmGOVMQpVS.java) ~[CMI-9.4.0.2.jar:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:170) ~[?:?]
	... 16 more
[18:11:07 INFO]: [CMI] Disabling CMI v9.4.0.2
[18:11:07 ERROR]: Error occurred (in the plugin loader) while disabling CMI v9.4.0.2 (Is it up to date?)
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:315) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1060) ~[CMI-9.4.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.4.jar:git-Paper-468]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-468]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[paper-1.19.4.jar:git-Paper-468]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-468]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-468]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "hgMZmBnTGPAmGOVMQpVS.sfr5bZI3NklRncWEG1SHj" is null
	at hgMZmBnTGPAmGOVMQpVS.RGHmdZuZn9ns7R(hgMZmBnTGPAmGOVMQpVS.java) ~[CMI-9.4.0.2.jar:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:170) ~[?:?]
	... 19 more
[18:11:07 INFO]: Running delayed init tasks
[18:11:07 INFO]: Done (6.625s)! For help, type "help"
[18:11:07 INFO]: Timings Reset

```

**Comment by yushijinhun** [comment]
CMI 插件为闭源，看不出报错原因。你可以尝试联系 CMI 插件作者解决。

**Comment by Shapaper** [comment]
我的mmo插件和RealisticSeasons都有一样的报错

**Comment by Shapaper** [comment]
@yushijinhun
