### ISSUE TITLE
1.20 服务端 + authlib-injector 1.2.2 启动报错，客户端皮肤无法显示

### ISSUE THREAD

**Issue by Mythologyli** [yushijinhun/authlib-injector#209]
服务端：Spigot 1.20 或 Paper 1.20
配合自建 Blessing Skin 皮肤站使用
问题：服务端启动报错，且客户端能看到自己的皮肤，但看到别人的皮肤均为默认皮肤

服务端启动日志
```
[authlib-injector] [INFO] Version: 1.2.2
[authlib-injector] [INFO] Authentication server: https://skin.akashic.cc/api/yggdrasil
[authlib-injector] [DEBUG] Metadata: {"meta":{"serverName":"Blessing Skin","implementationName":"Yggdrasil API for Blessing Skin","implementationVersion":"5.1.5","links":{"homepage":"https:\/\/skin.akashic.cc","register":"https:\/\/skin.akashic.cc\/auth\/register"},"feature.non_email_login":true},"skinDomains":["","skin.akashic.cc"],"signaturePublickey":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0Y\/at00O+cSsLiNhy3z\/\nXR16nf7OfDFCfJxYBODrSQnakr7u6ZYWzoFue6t3TMgo6lShM9VDDGhZTLEgFc+s\nMcQMmxiyCRnEh7Cd46bVuQfAFhHfZOanquvwRo0o7ZWExVMawFceKojnH6aEx4he\n6sZtj9dvEhCMOVSaNDE30VrKUCGpRSWvFMK6fEh8SCMzUBWv43dZ7HWOkEnwJtdG\nkdnMhUAyfYlWWGec3tplRMV8vkLkiHS6mu58M5OYTFDFLIktsIHhvq5lT80l8akI\niGm43Nb7d\/bapb7y7ObQUcyqWtXTiWsc\/wK+\/ILptaob1bGi+deIvr6PTbbe9pJW\n084d2hXVe06L2C7Wsaye0fIxEan6\/g74ysJkCVa0zl8T\/WijV+mpBmz\/jFI9gVH1\nKHRe17R6vCb5b0IaArUmcG0DueqEOs8VWbOs0XPN3xkc5AObORyXmkhXnGoSedSY\nBjzN+TcGaE9z4+cnneQ4k21nv2c\/0i7XkPG98g5KFtm3+SOhy7HnMg0qAH9epvnK\n4BiU5KKc2oJpCo\/d6uafPEFHpOxaqtIRx8Xu2JxKCL7bZm8BchfIf7+YWbAhNIdZ\nhsA2vogGPdFXW9QusEqFGOblmsbWUGyv+Ubf2eVOPfro83yxS9yIwCfsoRCz7PS6\neCzQjjqXJGjDHhttRYIBVuECAwEAAQ==\n-----END PUBLIC KEY-----\n"}
[authlib-injector] [DEBUG] Parsed metadata: APIMetadata [apiRoot=https://skin.akashic.cc/api/yggdrasil/, skinDomains=[, skin.akashic.cc], decodedPublickey=Optional[Sun RSA public key, 4096 bits
  params: null
  modulus: 854938089060717921562354674794380228504426603073171558784468571237393736351992368937323606456084865515254571286422760583530914933746925656359018610161055755631730079824927935866257930709187704770471589825637826513204872349230404620727868700372090238119130606972598967320031268736138346595757642437925582375602816535063324581923114550912727171260157114584047808838478988319452233418710952598777145811185222513671802010492383517669809517303977694626490221137499858792200856858368369531785007124768403983346455874424955794830693163150855047437509300262748637497115442438389947091422834719168286739921164085759392894532182889011003807167960435481681920190018387418668020106100994777396247658804912961368513117436223971044085312328981632577777264786907589782268051328857805359702416628915851478681590613104820169022601029571704776261395351471422619085203138556868795000517312069678520367588057161517459510391825489443377734858383478828553867553198819120126123832048488862487768923359066573908701890946901535893234737330750370052078017975991039185694358200041282251753647630435499410600757099999028075238113818249266366708797878796051376313452713906218551817148916232612696535558548575759180586420590787464821611670079432164499253184517857
  public exponent: 65537], meta={feature.non_email_login=true, implementationName=Yggdrasil API for Blessing Skin, implementationVersion=5.1.5, links={"homepage":"https:\/\/skin.akashic.cc","register":"https:\/\/skin.akashic.cc\/auth\/register"}, serverName=Blessing Skin}]
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2) Host: Linux 5.19.0-43-generic (amd64)
Loading libraries, please wait...
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [INFO] Transformed [com.mojang.authlib.minecraft.UserApiService] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [WARNING] Failed to register log handler on java.net.URLClassLoader@5e316c74
java.lang.NoSuchMethodException
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at moe.yushi.authlibinjector.transform.support.AuthlibLogInterceptor.invokeCreateMethod(AuthlibLogInterceptor.java:178)
        at moe.yushi.authlibinjector.transform.support.AuthlibLogInterceptor.registerLogHandle(AuthlibLogInterceptor.java:138)
        at moe.yushi.authlibinjector.transform.support.AuthlibLogInterceptor.onClassLoading(AuthlibLogInterceptor.java:64)
        at com.mojang.authlib.HttpAuthenticationService.<clinit>(HttpAuthenticationService.java)
        at net.minecraft.server.Main.main(Main.java:196)
        at org.bukkit.craftbukkit.Main.main(Main.java:316)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)

[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com] to [https://skin.akashic.cc/api/yggdrasil/authserver]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com] to [https://skin.akashic.cc/api/yggdrasil/authserver]
[authlib-injector] [INFO] Httpd is running on port 32825
[authlib-injector] [DEBUG] Transformed url [https://api.mojang.com] to [http://127.0.0.1:32825/https/api.mojang.com]
[authlib-injector] [DEBUG] Transformed url [https://sessionserver.mojang.com] to [http://127.0.0.1:32825/https/sessionserver.mojang.com]
[authlib-injector] [DEBUG] Transformed url [https://api.minecraftservices.com] to [http://127.0.0.1:32825/https/api.minecraftservices.com]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo] with [Yggdrasil Public Key Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[14:50:12 INFO]: Environment: authHost='https://skin.akashic.cc/api/yggdrasil/authserver', accountsHost='http://127.0.0.1:32825/https/api.mojang.com', sessionHost='http://127.0.0.1:32825/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:32825/https/api.minecraftservices.com', name='PROD'
[authlib-injector] [DEBUG] Reverse proxy: > GET https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys, headers: {cache-control=no-cache, pragma=no-cache, user-agent=Java/17.0.7, accept=text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}
[authlib-injector] [DEBUG] Reverse proxy: < 404 Not Found , headers: {date=[Sat, 10 Jun 2023 06:50:12 GMT], Cache-Control=[no-cache, private], Server=[nginx], X-Authlib-Injector-API-Location=[https://skin.akashic.cc/api/yggdrasil], Set-Cookie=[locale=en; expires=Sat, 10-Jun-2023 08:50:12 GMT; Max-Age=7200; path=/; httponly; samesite=lax], Vary=[Accept-Encoding], Content-Type=[text/html; charset=UTF-8]}
[14:50:12 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:119) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:91) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:94) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.lambda$get$1(YggdrasilServicesKeyInfo.java:81) ~[authlib-4.0.43.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientException: Failed to read value <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="robots" content="noindex,nofollow">
    <title>404 Not Found - Blessing Skin</title>
    <link href="/app/spectre.d5c09e2.css" rel="stylesheet" crossorigin="anonymous">
      </head>

  <body class="bg-gray">
    <div class="text-right m-2 p-2">
      <a href="https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys?lang=zh_CN"
      class="mx-2 p-1 label label-secondary"
    >中文 (简体)</a>
      <a href="https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys?lang=zh_TW"
      class="mx-2 p-1 label label-secondary"
    >中文 (正體)</a>
      <a href="https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys?lang=en"
      class="mx-2 p-1 label label-secondary"
    >English</a>
      <a href="https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys?lang=es_ES"
      class="mx-2 p-1 label label-secondary"
    >Español</a>
      <a href="https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys?lang=ru_RU"
      class="mx-2 p-1 label label-secondary"
    >Русский язык</a>
  </div>

    <div class="hero d-flex">
      <div class="hero-body text-center">
        <h1><a class="text-primary" href="https://skin.akashic.cc">Blessing Skin</a></h1>
        <div class="divider"></div>
        <h3 style="margin-top: 15vh;">404 Not Found</h3>
          <p>
    Details: Nothing here.
  </p>
        <div class="divider"></div>
              </div>
    </div>
      </body>
</html>

        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:32) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:97) ~[authlib-4.0.43.jar:?]
        ... 9 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:969) ~[gson-2.10.jar:?]
        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:97) ~[authlib-4.0.43.jar:?]
        ... 9 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:969) ~[gson-2.10.jar:?]
        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:97) ~[authlib-4.0.43.jar:?]
        ... 9 more
[14:50:13 INFO]: Loaded 7 recipes
[14:50:13 INFO]: Starting minecraft server version 1.20
```

客户端日志
```
[14:28:46] [Render thread/INFO]: Connecting to 192.168.8.159, 25565
[14:28:48] [Render thread/INFO]: New minimap session initialized!
[14:28:48] [Render thread/INFO]: New world map session initialized!
[14:28:48] [Render thread/INFO]: Started 10 worker threads
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] Plugins (7):
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[14:28:48] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[14:28:49] [Render thread/WARN]: Ignoring player info update for unknown player 8eca1c10-295a-3d6c-9b7b-b5e5d7e7f86d
[14:28:49] [Render thread/INFO]: [System] [CHAT] 欢迎来到 Akashic MC！
[14:28:49] [Render thread/INFO]: [System] [CHAT] 手持一个物品，然后使用 /leader 命令，可以查看这件物品的服务器统计信息！
[14:28:49] [Render thread/INFO]: [System] [CHAT] 可以使用 /slogan set xxx 设置在玩家列表显示的标语！
[14:28:49] [Render thread/INFO]: [System] [CHAT] Myth加入了游戏
[14:28:49] [Render thread/WARN]: Ignoring chat session from Myth due to missing Services public key
[14:28:49] [Render thread/WARN]: Ignoring chat session from TyphoonEx due to missing Services public key
[14:28:49] [Render thread/WARN]: Ignoring chat session from MaoTouZhu due to missing Services public key
[14:28:49] [Render thread/INFO]: Loaded 53 advancements
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 481.3 μs, totaling 3.234 ms.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 79.30 μs, totaling 403.1 ms.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 59.40 μs, totaling 2.909 ms.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] Plugins (7):
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[14:28:49] [Worker-Main-30/ERROR]: Property textures has been tampered with (signature invalid)
[14:28:49] [Worker-Main-30/INFO]: [STDOUT]: https://skin.akashic.cc/textures/c46516d240ee28b963b7d7a43322ba67e823e9666dbeaeb944012a4a16ce4dcf
[14:28:49] [Worker-Main-30/INFO]: [STDOUT]: https://skin.akashic.cc/textures/11ee73c90db4ac2e2a57c5ff34033b214248a6a23058f297d3648632aa31bca4
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[14:28:49] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 134.2 μs, totaling 1.904 ms.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 87.70 μs, totaling 319.5 ms.
[14:28:49] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 59.00 μs, totaling 1.055 ms.
[14:28:53] [Worker-Main-30/ERROR]: Property textures has been tampered with (signature invalid)
[14:28:53] [Worker-Main-31/ERROR]: Property textures has been tampered with (signature invalid)
[14:28:53] [Worker-Main-30/ERROR]: Property textures has been tampered with (signature invalid)
[14:28:53] [Worker-Main-31/ERROR]: Property textures has been tampered with (signature invalid)
```

查看 Blessing Skin 侧的 Nginx 日志发现请求过 `https://skin.akashic.cc/api/yggdrasil/minecraftservices/publickeys` 但 404 了，会不会是 Mojang 更改了相关协议呢

**Comment by SkyIce0229** [comment]
fabric1.20也出现了相同的问题

**Comment by Shanwer** [comment]
同，purpur1.20，authlib1.2.2

**Comment by Shanwer** [comment]
> 同，purpur1.20，authlib1.2.2

ps:基岩版可以看到其他玩家和自己的皮肤

**Comment by yushijinhun** [comment]
Fixed in https://github.com/yushijinhun/authlib-injector/commit/18a0ce266963e98c47b65df7a71450a857e100ef
