### ISSUE TITLE
Failed to retrieve profile key pair

### ISSUE THREAD

**Issue by sydeptraivc** [yushijinhun/authlib-injector#223]
Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.class_7434.method_43605(class_7434.java:130)
	at net.minecraft.class_7434.method_44291(class_7434.java:69)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Lama3L9R** [comment]
According to [Fabric 1.20.4 JavaDOC](https://maven.fabricmc.net/docs/yarn-1.20.4+build.3/net/minecraft/client/session/ProfileKeysImpl.html#fetchKeyPair(com.mojang.authlib.minecraft.UserApiService ) probably you are facing bad Internet connection. Please confirm that you can connect to Mojang's server
