### ISSUE TITLE
不支持 Java 21？

### ISSUE THREAD

**Issue by zkitefly** [yushijinhun/authlib-injector#224]
听别人说，是 AuthLib Injector 带的 ASM 库还不支持 Java 21？

[错误报告-2023-10-1_11.06.51.zip](https://github.com/yushijinhun/authlib-injector/files/12776055/-2023-10-1_11.06.51.zip)

这个是来自 HMCL KOOK 上的一个日志，其中 authlib-injector.log：

```
Logging started at 2023-10-01T03:04:22.511164600Z
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
[authlib-injector] [WARNING] Failed to transform [org/xml/sax/SAXException]
java.lang.IllegalArgumentException: Unsupported class file major version 65
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.getClassReader(ClassTransformer.java:118)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.getStringConstants(ClassTransformer.java:128)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.access$000(ClassTransformer.java:52)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle$TransformContextImpl.getStringConstants(ClassTransformer.java:66)
	at moe.yushi.authlibinjector.transform.support.PaperUsernameCheckTransformer.transform(PaperUsernameCheckTransformer.java:34)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.accept(ClassTransformer.java:146)
	at moe.yushi.authlibinjector.transform.ClassTransformer.transform(ClassTransformer.java:288)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1277)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2393)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:140)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:669)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:243)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:533)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:457)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.getLogger(Log4jLogHandler.java:58)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:51)
	at net.fabricmc.loader.impl.util.log.BuiltinLogHandler.replay(BuiltinLogHandler.java:128)
	at net.fabricmc.loader.impl.util.log.Log.init(Log.java:34)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:374)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:345)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
......
```

**Comment by HongYunCloud** [comment]
fixed at https://github.com/yushijinhun/authlib-injector/commit/df8299b8e747dcb8f25eca642145c8735bea6d9f
