### ISSUE TITLE
Authlib-injector not having a velocity.json file

### ISSUE THREAD

**Issue by WhoisDarkyXD** [yushijinhun/authlib-injector#239]
[15:06:45 ERROR]: Unable to load plugin plugins\authlib-injector.jar
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:67) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:364) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        
     starting argument used - java -Xmx1G -Xms512M -javaagent:"{path}\authlib-injector.jar=ely.by" -jar server.jar nogui
 NOTE :- {path} is the file path, the jar file is in the same directory as the server
  velocity version :- 3.3.0 snapshot

**Comment by burningtnt** [comment]
DO NOT put `authlib-injector` inside the plugin dir. Put it under other directionary
