### ISSUE TITLE
玩家尝试进入服务器时报错

### ISSUE THREAD

**Issue by solitary-sails** [yushijinhun/authlib-injector#242]
报错后玩家被提示"无法连接到认证服务器".服务端输出的日志如下
```
[authlib-injector] [WARNING] Reverse proxy error
java.io.IOException: Failed to select a proxy
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1229)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
	at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:197)
	at moe.yushi.authlibinjector.httpd.URLProcessor.access$400(URLProcessor.java:47)
	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:158)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: type HTTP is not compatible with address local:12345
	at java.base/java.net.Proxy.<init>(Proxy.java:95)
	at TRANSFORMER/mu_tong_fuck_check@1.0-SNAPSHOT/me.cunzai.mod.nointernet.MuTongFuckCheck$NoInternetProxySelector.select(MuTongFuckCheck.java:49)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227)
	... 12 more
```

**Comment by solitary-sails** [comment]
添加到启动参数里的内容为
`-javaagent:./authlib-injector.jar=https://littleskin.cn/api/yggdrasil`
