### ISSUE TITLE
Java11+ 上不兼容 MC 1.15.2 + Optifine

### ISSUE THREAD

**Issue by pentyum** [yushijinhun/authlib-injector#61]
安装optifine后，authlib无法使用，必须改成离线启动。Optifine版本为G1_pre1
错误记录：
```
[15:39:22] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[15:39:22] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[15:39:23] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:39:23] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
Caused by: java.lang.NoClassDefFoundError: moe/yushi/authlibinjector/transform/CallbackEntryPoint
	at net.minecraft.client.main.Main.main(SourceFile) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: moe.yushi.authlibinjector.transform.CallbackEntryPoint
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:185) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile) ~[Main.class:?]
	... 6 more
```

**Comment by pentyum** [comment]
目前OptiFine 1.15.2 HD U G1 pre10仍然存在该问题。

**Comment by EnterFor** [comment]
> 目前OptiFine 1.15.2 HD U G1 pre10仍然存在该问题。

你用的是Forge载入吗

**Comment by pentyum** [comment]
> > 目前OptiFine 1.15.2 HD U G1 pre10仍然存在该问题。
> 
> 你用的是Forge载入吗

不是，原版载入。但是用fabric载入能正常

**Comment by EnterFor** [comment]
1.15的高清修复一直不支持Forge的，官网有写。

**Comment by yushijinhun** [comment]
我使用 HMCL 安装了一个带 optifine 的 1.15.2，并未遇到任何问题。

我测试使用的环境：
* HMCL: 3.2-snapshot (https://github.com/huanghongxun/HMCL/commit/63e2fdf56dc95a005cec61504cbc908affad5040)
* authlib-injector: 1.1.27-5ef5f8e
* optifine: 1.15.2_HD_U_G1_pre13

@pentyum 请再次测试并提供详细的重现方法。

**Comment by pentyum** [comment]
> 我使用 HMCL 安装了一个带 optifine 的 1.15.2，并未遇到任何问题。
> 
> 我测试使用的环境：
> 
> * HMCL: 3.2-snapshot ([huanghongxun/HMCL@63e2fdf](https://github.com/huanghongxun/HMCL/commit/63e2fdf56dc95a005cec61504cbc908affad5040))
> * authlib-injector: 1.1.27-5ef5f8e
> * optifine: 1.15.2_HD_U_G1_pre13
> 
> @pentyum 请再次测试并提供详细的重现方法。

使用HMCL下载1.15.2，然后用启动器自带的自动安装来安装optifine_pre13，然后如果使用authlib登录方式来启动1.15.2就会报这样的错，改成离线则可以启动。

**Comment by yushijinhun** [comment]
@pentyum 

请把 HMCL 更新至[最新版](https://github.com/huanghongxun/HMCL/releases/latest)再尝试一下，如果问题依旧，请：
* 通过 HMCL 的**测试游戏**按钮启动 MC，将**游戏日志**导出并上传。
* 随后在**启动器设置**中导出**启动器日志**并上传。
* 将该 MC 版本的 JSON 文件上传（如 `.minecraft/versions/1.15.2_HD_U_G1_pre13/1.15.2_HD_U_G1_pre13.json`）。

**Comment by pentyum** [comment]
> @pentyum
> 
> 请把 HMCL 更新至[最新版](https://github.com/huanghongxun/HMCL/releases/latest)再尝试一下，如果问题依旧，请：
> 
> * 通过 HMCL 的**测试游戏**按钮启动 MC，将**游戏日志**导出并上传。
> * 随后在**启动器设置**中导出**启动器日志**并上传。
> * 将该 MC 版本的 JSON 文件上传（如 `.minecraft/versions/1.15.2_HD_U_G1_pre13/1.15.2_HD_U_G1_pre13.json`）。

已经更新了一下，还是无法启动
日志和json链接: https://pan.baidu.com/s/1knZhbN09L-7bUh2ABd7x3w 提取码: g1n5

**Comment by yushijinhun** [comment]
在 OpenJDK 14 上重现此 bug，OpenJDK 8 上未重现。

**Comment by yushijinhun** [comment]
这个 bug 实际上是 #33 的一个回归，#68 中的 fix 实际与 #34 等同，#34 中的 fix 后来被 #38 取代。由此可见，#38 中的 fix 在某些情况下还是有疏漏的。暂时先双管齐下，等有空了（或遇到其他问题）再重新考虑下这个问题。
