### ISSUE TITLE
服务器启用authlib-injector后原因不明的报错

### ISSUE THREAD

**Issue by Wishing-Qi** [yushijinhun/authlib-injector#77]
在1.12.2的spigot服务器中启用authlib-injector后出现原因不明的报错，尝试在Yum插件内将涉及到的插件与网站加入白名单，无果，现将报错代码与日志贴在下面

**Comment by Wishing-Qi** [comment]
authlib-injector.httpd] [WARNING] An error occurred while processing request [/https/api.mojang.com/profiles/minecraft]
java.io.UncheckedIOException: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryUUIDs(YggdrasilClient.java:66)
at moe.yushi.authlibinjector.httpd.QueryUUIDsFilter.performQuery(QueryUUIDsFilter.java:82)
at moe.yushi.authlibinjector.httpd.QueryUUIDsFilter.handle(QueryUUIDsFilter.java:63)
at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:131)
at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:410)
at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:116)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
at moe.yushi.authlibinjector.util.IOUtils.http(IOUtils.java:66)
at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryUUIDs(YggdrasilClient.java:62)
... 6 more

**Comment by Wishing-Qi** [comment]
[latest.log](https://github.com/yushijinhun/authlib-injector/files/5039223/latest.log)

**Comment by Wishing-Qi** [comment]
ava -Xmx2000M -XX:+AggressiveOpts -XX:+UseCompressedOops -javaagent:authlib-injector.jar=https://littlesk.in/api/yggdrasil -jar spigot-1.12.2.jar

**Comment by Wishing-Qi** [comment]
目前实际使用暂未受到影响，不过报错已经影响到查看服务器日志，望作者尽快修复

**Comment by hempflower** [comment]
你可以暂时使用此地址:`https://mcskin.littleservice.cn/api/yggdrasil`

此问题应该是authlib-injector没有正确处理重定向情况所致。

**Comment by yushijinhun** [comment]
Please add `-Dauthlibinjector.debug=all` parameter to commandline and paste **console output** here. (note that authlib-injector logs are not included in log files)

**Comment by yushijinhun** [comment]
这个问题应该是由 HTTP 重定向造成的，我会新开一个 issue 来讨论 authlib-injector 对于 HTTP 3xx 重定向应该如何处理。
