### ISSUE TITLE
是否支持Geyser？

### ISSUE THREAD

**Issue by mcoo** [yushijinhun/authlib-injector#96]
https://github.com/GeyserMC/Geyser/issues/1611#issue-755175599
服务器版本：Paper-246 MC: 1.16.3
登录过程中出现 问题
```
[19:03:49 INFO]: [Geyser-Spigot] Player connected with username ZiHang6
[authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.AuthenticationService] with [Constant URL Transformer]

[19:04:11 WARN]: Exception in thread "Thread-13" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
[19:04:11 WARN]:        at com.google.gson.Gson.assertFullConsumption(Gson.java:863)
[19:04:11 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:826)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.processResponse(HTTP.java:140)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.performPostRequest(HTTP.java:127)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:69)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:201)
[19:04:11 WARN]:        at com.github.steveice10.mc.protocol.MinecraftProtocol.createAuthServiceForPasswordLogin(MinecraftProtocol.java:284)
[19:04:11 WARN]:        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:244)
[19:04:11 WARN]:        at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$2(GeyserSession.java:417)
[19:04:11 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:04:11 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
[19:04:11 WARN]:        at com.google.gson.Gson.assertFullConsumption(Gson.java:859)
[19:04:11 WARN]:        ... 9 more
```

**Comment by AkameMoe** [comment]
这个问题你应该去找Geyser的团队，而不是authlib-injector的

**Comment by developer-ken** [comment]
`Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $`
Json标准问题？

**Comment by yushijinhun** [comment]
这是因为你用的验证服务器返回了畸形的数据，你可以尝试用 wireshark 抓一下包看看验证服务器返回了什么（如果是 HTTPS 流量可能还需要 [extract-tls-secrets](https://github.com/neykov/extract-tls-secrets)）。
