### ISSUE TITLE
关于 java11 paper 服务端的使用

### ISSUE THREAD

**Issue by thanksshu** [yushijinhun/authlib-injector#97]
根据paper论坛提出的：(https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615)

> When Minecraft 1.17 is released and Paper is updated to support it, Paper will bump the JVM requirement to Java 11. Any servers still using Java 8 to run Paper will need to be updated.

服务端（paper 1.16.4 #311）在启动时：

> Please update the version of Java you use to run Paper

想请问是否支持 java 11？

**Comment by yushijinhun** [comment]
是支持的，你可以试一下。

**Comment by thanksshu** [comment]
[实际使用java11时玩家连接会出现如下错误导致无法连接，我使用了(server.pro)进行托管。

[WARNING] ....[authlib-injector] Reverse proxy error

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)

at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)

at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)

at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)

at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)

at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)

at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)

at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)

at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:187)

at moe.yushi.authlibinjector.httpd.URLProcessor.access$300(URLProcessor.java:46)

at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:148)

at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)

at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)

at java.base/java.lang.Thread.run(Unknown Source)

[INFO] Disconnecting com.mojang.authlib.GameProfile@4f82ecd2[id=<null>,name=_用户名_,properties={},legacy=false] (/_IP:PORT_): Authentication servers are down. Please try again later, sorry!

[ERROR] .... Couldn't verify username because servers are unavailable

[INFO] .... com.mojang.authlib.GameProfile@4f82ecd2[id=<null>,name=_用户名_,properties={},legacy=false] (/_IP:PORT_) lost connection: Authentication servers are down. Please try again later, sorry!

**Comment by yushijinhun** [comment]
看起来是你验证服务器 TLS 配置的问题，请提供一下你验证服务器的地址。

**Comment by thanksshu** [comment]
启动参数如下：-server -Xms1024M -Xmx1024M -javaagent:authlib-injector-1.1.34.jar=https://littleskin.cn/api/yggdrasil -jar /pro/bin/mc/paper-spigot/1.16.4/paper-1.16.4.jar

**Comment by yushijinhun** [comment]
我无法复现你的问题，我觉得这与 PaperSpigot 以及 Java 11 无关。麻烦你在本地测试一下你的服务端，看看是否正常。

**Comment by thanksshu** [comment]
确实如此，已确认是托管服务的问题，十分感谢。
